# Traitement peut accéder à Ingestion (Kafka)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traitement-to-ingestion
  namespace: ingestion
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: payments-cluster
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traitement
      ports:
        - port: 9092
---
# Traitement peut accéder à Stockage (MinIO)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traitement-to-stockage
  namespace: stockage
spec:
  podSelector:
    matchLabels:
      app: minio
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traitement
      ports:
        - port: 9000
